name: 'Never Gonna Give You Up'
description: 'Never Gonna Let You Down'
runs:
  using: "composite"
  steps:
    - run: echo "Never gonna give you up"
      shell: bash
    - id: ls-that-container 
      run: ls $GITHUB_ACTION_PATH
      shell: bash
    - id: singing-real-good
      run: $GITHUB_ACTION_PATH/letyoudown.sh
      shell: bash
